version: "3.9"

services:
  focus-front:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: focus-front
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - focus-api

  focus-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: focus-api
    restart: unless-stopped
    volumes:
      - focus_api_data:/app/db

volumes:
  focus_api_data:
