server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location /css/ {
        try_files $uri =404;
    }

    location /js/ {
        try_files $uri =404;
    }

    location /assets/ {
        try_files $uri =404;
    }

    location / {
        try_files $uri /index.html;
    }
}