const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
    addCompany: (name) => ipcRenderer.invoke('add-company', name),
    getCompanies: () => ipcRenderer.invoke('get-companies'),

    addBankAccount: (data) => ipcRenderer.invoke('add-bank-account', data),
    updateBankAccount: (data) => ipcRenderer.invoke('update-bank-account', data),
    deleteBankAccount: (bankAccountId) => ipcRenderer.invoke('delete-bank-account', bankAccountId),
    getBankAccounts: (companyId) => ipcRenderer.invoke('get-bank-accounts', companyId),
    selectRib: () => ipcRenderer.invoke('select-rib'),

    selectPdf: () => ipcRenderer.invoke('select-pdf'),
    addStatement: (data) => ipcRenderer.invoke('add-statement', data),
    addStatementsBulk: (data) => ipcRenderer.invoke('add-statements-bulk', data),
    getStatements: (bankAccountId) => ipcRenderer.invoke('get-statements', bankAccountId),
    deleteStatement: (statementId) => ipcRenderer.invoke('delete-statement', statementId),

    getTransactions: (data) => ipcRenderer.invoke('get-transactions', data),
    getTransaction: (transactionId) => ipcRenderer.invoke('get-transaction', transactionId),
    updateTransactionStatus: (data) => ipcRenderer.invoke('update-transaction-status', data),
    updateTransactionDetails: (data) => ipcRenderer.invoke('update-transaction-details', data),
    getTransactionSummary: (data) => ipcRenderer.invoke('get-transaction-summary', data),
    getAvailablePeriods: (bankAccountId) => ipcRenderer.invoke('get-available-periods', bankAccountId),
    getDashboardInsights: (data) => ipcRenderer.invoke('get-dashboard-insights', data),
    selectSmartReceipt: (bankAccountId) => ipcRenderer.invoke('select-smart-receipt', bankAccountId),

    selectReceipt: () => ipcRenderer.invoke('select-receipt'),
    addReceipt: (data) => ipcRenderer.invoke('add-receipt', data),
    getReceipts: (transactionId) => ipcRenderer.invoke('get-receipts', transactionId),
    deleteReceipt: (receiptId) => ipcRenderer.invoke('delete-receipt', receiptId),

    getCategoryRules: () => ipcRenderer.invoke('get-category-rules'),
    addCategoryRule: (data) => ipcRenderer.invoke('add-category-rule', data),
    bulkUpdateTransactions: (data) => ipcRenderer.invoke('bulk-update-transactions', data),

    selectCashSheets: () => ipcRenderer.invoke('select-cash-sheets'),
    importCashSheets: (data) => ipcRenderer.invoke('import-cash-sheets', data),
    getCashSheetInsights: (data) => ipcRenderer.invoke('get-cash-sheet-insights', data),
    getCompanyDashboard: (companyId) => ipcRenderer.invoke('get-company-dashboard', companyId),
    getCashSheetReminders: () => ipcRenderer.invoke('get-cash-sheet-reminders'),

    selectDocuments: () => ipcRenderer.invoke('select-documents'),
    addDocuments: (data) => ipcRenderer.invoke('add-documents', data),
    getDocuments: (data) => ipcRenderer.invoke('get-documents', data),
    deleteDocument: (documentId) => ipcRenderer.invoke('delete-document', documentId),
    findDocumentMatches: (data) => ipcRenderer.invoke('find-document-matches', data),
    searchTransactionsForDocument: (data) => ipcRenderer.invoke('search-transactions-for-document', data),
    linkDocumentToTransaction: (data) => ipcRenderer.invoke('link-document-to-transaction', data),

    getThirdParties: (data) => ipcRenderer.invoke('get-third-parties', data),
    backfillThirdParties: (data) => ipcRenderer.invoke('backfill-third-parties', data),
    updateTransactionThirdParty: (data) => ipcRenderer.invoke('update-transaction-third-party', data),
    getDocumentsDashboard: (data) => ipcRenderer.invoke('get-documents-dashboard', data),
    renameDocument: (data) => ipcRenderer.invoke('rename-document', data),
    getDocumentTree: (data) => ipcRenderer.invoke('get-document-tree', data),
    toggleDocumentFavorite: (documentId) => ipcRenderer.invoke('toggle-document-favorite', documentId),
    updateDocumentTags: (data) => ipcRenderer.invoke('update-document-tags', data),
    getDocumentDuplicates: (data) => ipcRenderer.invoke('get-document-duplicates', data),
    getDocumentSmartFolders: (data) => ipcRenderer.invoke('get-document-smart-folders', data),
    toggleDocumentImportant: (documentId) => ipcRenderer.invoke('toggle-document-important', documentId),
    updateDocumentThirdParty: (data) => ipcRenderer.invoke('update-document-third-party', data),
    getDocumentHistory: (documentId) => ipcRenderer.invoke('get-document-history', documentId),
    restoreDocument: (documentId) => ipcRenderer.invoke('restore-document', documentId),
    deleteDocumentPermanently: (documentId) => ipcRenderer.invoke('delete-document-permanently', documentId),
    updateDocumentType: (data) => ipcRenderer.invoke('update-document-type', data),
    moveDocumentFolder: (data) => ipcRenderer.invoke('move-document-folder', data),
    moveDocument: (data) => ipcRenderer.invoke('move-document', data),
    updateThirdParty: (data) => ipcRenderer.invoke('update-third-party', data),
    mergeThirdParties: (data) => ipcRenderer.invoke('merge-third-parties', data),
    cleanupThirdParties: (data) => ipcRenderer.invoke('cleanup-third-parties', data),
    createAutomationRule: (data) => ipcRenderer.invoke('create-automation-rule', data),
    getAutomationRules: (data) => ipcRenderer.invoke('get-automation-rules', data),
    deleteAutomationRule: (ruleId) => ipcRenderer.invoke('delete-automation-rule', ruleId),
    applyAutomationRules: (data) => ipcRenderer.invoke('apply-automation-rules', data),

    openFile: (filepath) => ipcRenderer.invoke('open-file', filepath),

    createBackup: () => ipcRenderer.invoke('create-backup'),
    openDataFolder: () => ipcRenderer.invoke('open-data-folder')
});
